/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type GetManyUserResponseDto = {
  data: User[];
  count: number;
  total: number;
  page: number;
  pageCount: number;
};

export type User = {
  id: string;
  username: string;
  password: string;
  posts: string[];
};

export type CreateManyUserDto = {
  bulk: User[];
};

export type GetManyPostResponseDto = {
  data: Post[];
  count: number;
  total: number;
  page: number;
  pageCount: number;
};

export type Post = {
  id: string;
  title: string;
  userId: string;
};

export type CreateManyPostDto = {
  bulk: Post[];
};
